nohup: ignoring input
[2025-06-05 16:44:51 +0000] [238542] [INFO] Starting gunicorn 23.0.0
[2025-06-05 16:44:51 +0000] [238542] [INFO] Listening at: http://0.0.0.0:5000 (238542)
[2025-06-05 16:44:51 +0000] [238542] [INFO] Using worker: sync
[2025-06-05 16:44:51 +0000] [238544] [INFO] Booting worker with pid: 238544
/root/David/myenv/lib/python3.12/site-packages/razorpay/client.py:4: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
[2025-06-05 16:45:31 +0000] [238542] [INFO] Handling signal: hup
[2025-06-05 16:45:31 +0000] [238542] [INFO] Hang up: Master
[2025-06-05 16:45:31 +0000] [238542] [ERROR] Worker (pid:238544) was sent SIGHUP!
[2025-06-05 16:45:31 +0000] [238686] [INFO] Booting worker with pid: 238686
/root/David/myenv/lib/python3.12/site-packages/razorpay/client.py:4: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
[2025-06-06 06:55:46,994] ERROR in app: Exception on /admin/add-book [POST]
Traceback (most recent call last):
  File "/root/David/myenv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/David/myenv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/David/myenv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/David/myenv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/David/admin_routes.py", line 20, in decorated_function
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/root/David/admin_routes.py", line 306, in add_book
    image.save(os.path.join(current_app.config['UPLOAD_FOLDER'], 'books', image_filename))
  File "/root/David/myenv/lib/python3.12/site-packages/werkzeug/datastructures/file_storage.py", line 129, in save
    dst = open(dst, "wb")
          ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'static/uploads/books/WhatsApp_Image_2025-06-06_at_12.22.42.jpeg'
[2025-06-06 06:56:07,703] ERROR in app: Exception on /admin/add-book [POST]
Traceback (most recent call last):
  File "/root/David/myenv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/David/myenv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/David/myenv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/David/myenv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/David/admin_routes.py", line 20, in decorated_function
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/root/David/admin_routes.py", line 306, in add_book
    image.save(os.path.join(current_app.config['UPLOAD_FOLDER'], 'books', image_filename))
  File "/root/David/myenv/lib/python3.12/site-packages/werkzeug/datastructures/file_storage.py", line 129, in save
    dst = open(dst, "wb")
          ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'static/uploads/books/WhatsApp_Image_2025-06-06_at_12.22.42.jpeg'
[2025-06-06 06:56:13,473] ERROR in app: Exception on /admin/add-book [POST]
Traceback (most recent call last):
  File "/root/David/myenv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/David/myenv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/David/myenv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/David/myenv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/David/admin_routes.py", line 20, in decorated_function
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/root/David/admin_routes.py", line 306, in add_book
    image.save(os.path.join(current_app.config['UPLOAD_FOLDER'], 'books', image_filename))
  File "/root/David/myenv/lib/python3.12/site-packages/werkzeug/datastructures/file_storage.py", line 129, in save
    dst = open(dst, "wb")
          ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'static/uploads/books/WhatsApp_Image_2025-06-06_at_12.22.42.jpeg'
[2025-06-06 06:57:01,344] ERROR in app: Exception on /admin/add-book [POST]
Traceback (most recent call last):
  File "/root/David/myenv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/David/myenv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/David/myenv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/David/myenv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/David/admin_routes.py", line 20, in decorated_function
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/root/David/admin_routes.py", line 306, in add_book
    image.save(os.path.join(current_app.config['UPLOAD_FOLDER'], 'books', image_filename))
  File "/root/David/myenv/lib/python3.12/site-packages/werkzeug/datastructures/file_storage.py", line 129, in save
    dst = open(dst, "wb")
          ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'static/uploads/books/WhatsApp_Image_2025-06-06_at_12.22.42.jpeg'
[2025-06-06 06:58:13,976] ERROR in app: Exception on /admin/add-book [POST]
Traceback (most recent call last):
  File "/root/David/myenv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/David/myenv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/David/myenv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/David/myenv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/David/admin_routes.py", line 20, in decorated_function
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/root/David/admin_routes.py", line 306, in add_book
    image.save(os.path.join(current_app.config['UPLOAD_FOLDER'], 'books', image_filename))
  File "/root/David/myenv/lib/python3.12/site-packages/werkzeug/datastructures/file_storage.py", line 129, in save
    dst = open(dst, "wb")
          ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'static/uploads/books/WhatsApp_Image_2025-06-06_at_12.22.42.jpeg'
[2025-06-06 07:09:04,614] ERROR in app: Exception on /admin/add-book [POST]
Traceback (most recent call last):
  File "/root/David/myenv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/David/myenv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/David/myenv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/David/myenv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/David/admin_routes.py", line 20, in decorated_function
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/root/David/admin_routes.py", line 306, in add_book
    image.save(os.path.join(current_app.config['UPLOAD_FOLDER'], 'books', image_filename))
  File "/root/David/myenv/lib/python3.12/site-packages/werkzeug/datastructures/file_storage.py", line 129, in save
    dst = open(dst, "wb")
          ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'static/uploads/books/WhatsApp_Image_2025-06-06_at_12.22.42.jpeg'
[2025-06-06 07:09:11,148] ERROR in app: Exception on /admin/add-book [POST]
Traceback (most recent call last):
  File "/root/David/myenv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/David/myenv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/David/myenv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/David/myenv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/David/admin_routes.py", line 20, in decorated_function
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/root/David/admin_routes.py", line 306, in add_book
    image.save(os.path.join(current_app.config['UPLOAD_FOLDER'], 'books', image_filename))
  File "/root/David/myenv/lib/python3.12/site-packages/werkzeug/datastructures/file_storage.py", line 129, in save
    dst = open(dst, "wb")
          ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'static/uploads/books/WhatsApp_Image_2025-06-06_at_12.22.42.jpeg'
[2025-06-06 07:09:16,229] ERROR in app: Exception on /admin/add-book [POST]
Traceback (most recent call last):
  File "/root/David/myenv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/David/myenv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/David/myenv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/David/myenv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/David/admin_routes.py", line 20, in decorated_function
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/root/David/admin_routes.py", line 306, in add_book
    image.save(os.path.join(current_app.config['UPLOAD_FOLDER'], 'books', image_filename))
  File "/root/David/myenv/lib/python3.12/site-packages/werkzeug/datastructures/file_storage.py", line 129, in save
    dst = open(dst, "wb")
          ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'static/uploads/books/WhatsApp_Image_2025-06-06_at_12.22.42.jpeg'
[2025-06-06 07:10:28,974] ERROR in app: Exception on /admin/add-book [POST]
Traceback (most recent call last):
  File "/root/David/myenv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/David/myenv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/David/myenv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/David/myenv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/David/admin_routes.py", line 20, in decorated_function
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/root/David/admin_routes.py", line 306, in add_book
    image.save(os.path.join(current_app.config['UPLOAD_FOLDER'], 'books', image_filename))
  File "/root/David/myenv/lib/python3.12/site-packages/werkzeug/datastructures/file_storage.py", line 129, in save
    dst = open(dst, "wb")
          ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'static/uploads/books/WhatsApp_Image_2025-06-06_at_12.22.42.jpeg'
